title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://stefansonntag.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
